config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'campgrounds#index'
    resources :users, only: [:index, :show, :update]
    resources :campgrounds, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :show, :destroy] do
      collection do
        get 'search'
      end
    end

  end

  scope module: :public do
    root to: 'homes#top'
    resource :users, only: [:show, :edit, :update] do
      collection do
        get 'favorite'
        get 'information/edit' => 'users#edit', as: 'edit'
        patch 'information/update' => 'users#update', as: 'update'
      end
    end
    resources :campgrounds, only: [:new, :index, :show, :create] do
      collection do
        get 'map'
        get 'thanks'
        get 'status'
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
    end
    resources :reviews, only: [:new, :index, :create, :destroy]
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reviews = Review.page(params[:page])
  end

  def search
    @q = Review.ransack(params[:q])
    @reviews = @q.result(distinct: true).page(params[:page])
  end
  
  def destroy
    review = Review.find(params[:id])

    review.destroy
    redirect_back fallback_location: root_path, notice:'削除完了しました'
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="container">
  <div class="text-center p-1">
    <h3>レビュー一覧</h3>
  <div class="row">
    <div class="col d-flex justify-content-center">
      <div class="form-group form-inline">
        <%= search_form_for @q, url: search_admin_reviews_path do |f| %>
          <%= f.search_field :user_name_cont, class: "form-control mx-auto", placeholder: ' ユーザー名で検索' %>
          <%= f.submit '検索', class: "form-control" %>
        <% end %>
      </div>
      <div class="form-check">
        <%= search_form_for @q, url: search_admin_reviews_path do |f| %>
          <%= f.label :"文章解析", class: "form-check-label" %>
          <%= f.radio_button :score_gteq, '0.5', class: "form-check-input-radio" %><%= f.label :"良感情", class: "form-check-label" %>
          <%= f.radio_button :score_lteq, '-0.5', class: "form-check-input-radio" %><%= f.label :"悪感情", class: "form-check-label" %>
          <%= f.submit '検索', class: "form-control" %>
        <% end %>
      </div>
    </div>
  </div>
  </div>
  <div class="mt-3">
    <%= render 'layouts/reviews', reviews: @reviews %>
  </div>
</div>

app/views/admin/reviews/search.html.erb
<div class="container">
  <div class="text-center p-1">
    <h3>レビュー一覧</h3>
    <div class="form-group form-inline">
      <%= search_form_for @q, url: search_admin_reviews_path do |f| %>
        <%= f.search_field :user_name_cont, class: "form-control mx-auto", placeholder: ' ユーザー名で検索' %>
        <%= f.submit '検索', class: "form-control" %>
      <% end %>
    </div>
    <div class="form-check form-inline">
      <%= search_form_for @q, url: search_admin_reviews_path do |f| %>
        <%= f.label :"文章解析", class: "form-check-label" %>
        <%= f.radio_button :score_gteq, '0.5', class: "form-check-input-radio" %><%= f.label :"良感情", class: "form-check-label" %>
        <%= f.radio_button :score_lteq, '-0.5', class: "form-check-input-radio" %><%= f.label :"悪感情", class: "form-check-label" %>
        <%= f.submit '検索', class: "form-control" %>
      <% end %>
    </div>
  </div>
  <div class="mt-3">
    <%= render 'layouts/reviews', reviews: @reviews %>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<h1>Admin::Reviews#show</h1>
<p>Find me in app/views/admin/reviews/show.html.erb</p>