config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'campgrounds#index'
    resources :users, only: [:index, :show, :update]
    resources :campgrounds, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :show, :destroy] do
      collection do
        get 'search'
      end
    end

  end

  scope module: :public do
    root to: 'homes#top'
    resource :users, only: [:show, :edit, :update] do
      collection do
        get 'favorite'
        get 'information/edit' => 'users#edit', as: 'edit'
        patch 'information/update' => 'users#update', as: 'update'
      end
    end
    resources :campgrounds, only: [:new, :index, :show, :create] do
      collection do
        get 'map'
        get 'thanks'
        get 'status'
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
    end
    resources :reviews, only: [:new, :index, :create, :destroy]
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/campground.rb
class Campground < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :camptags, dependent: :destroy
  has_many :tags, through: :camptags

  belongs_to :user, optional: true

  enum is_confirmed: {pending: 0, confirmed: 1, rejected: 2}

  has_one_attached :image

  validates :name, presence: true
  validates :address, presence: true
  validates :check_in, presence: true
  validates :check_out, presence: true

  # Geocodeを使うための設定
  geocoded_by :address
  after_validation :geocode, if: :address_changed?


  # Ransackを使うための設定
  def self.ransackable_attributes(auth_object = nil)
    ["address", "business_hours", "busstop_line", "busstop_name", "busstop_walk", "camp_url", "check_in", "check_out", "created_at", "description", "id", "is_confirmed", "latitude", "longitude", "name", "phone_number", "rating", "rejection_reason", "station_line", "station_name", "station_walk", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["camptags", "reviews", "tags", "user"]
  end

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewtagとする
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete　Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end

  
  # 既にブックマークされているか確認
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # レビューの平均値を算出
  def avg_score
    unless self.reviews.empty?
      reviews.average(:star).round(1)
    else
      0.0
    end
  end

  # 画像がない場合、デフォルト画像を表示する
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/camping-icon.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/campgrounds_controller.rb
class Admin::CampgroundsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @campground = Campground.new
  end

  def index
    @campgrounds = Campground.page(params[:page])

  end

  def show
    @campground = Campground.find(params[:id])
    @campground_tags = @campground.tags
  end

  def edit
    @campground = Campground.find(params[:id])
    @tag_list = @campground.tags.pluck(:tag_name).join(',')
  end

  def create
    @campground = Campground.new(campground_params)
    @campground.is_confirmed = 1

    # タグを,で区切り配列にする
    tag_list = params[:campground][:tag_name].split(',')

    if @campground.save
      @campground.save_tag(tag_list)
      redirect_to admin_campgrounds_path, notice:'投稿完了しました'
    else
      render:new
    end
  end

  def update
    @campground = Campground.find(params[:id])

    tag_list = params[:campground][:tag_name].split(',')

    if @campground.update(campground_params)
      # campground.idに紐付いたtagを削除する
      @old_relations = Camptag.where(campground_id: @campground.id)
      @old_relations.each do |relation|
        relation.delete
      end

      @campground.save_tag(tag_list)
      redirect_to admin_campground_path(@campground.id), notice:'編集完了しました'
    else
      render:edit
    end
  end

  def destroy
    Campground.find(params[:id]).destroy

    redirect_to admin_campgrounds_path
  end


  private

  def campground_params
    params.require(:campground).permit(:user_id, :name, :description, :address, :latitude, :longitude, :phone_number, :business_hours,
    :check_in, :check_out, :station_line, :station_name, :station_walk, :busstop_line, :busstop_name, :busstop_walk, :rejection_reason,
    :camp_url, :rating, :is_confirmed, :image)
  end
end

app/helpers/admin/campgrounds_helper.rb
module Admin::CampgroundsHelper
end

app/views/admin/campgrounds/edit.html.erb
<div class="container">
  <div class="text-center p-1">
    <h3>キャンプ場編集</h3>
  </div>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= form_with model: @campground, url: admin_campground_path, method: :patch, class: 'new_campground', local: true do |f| %>
      <%= render "public/shared/error_messages", resource: @campground %>
        <div class="actions p-1">
          <%= f.submit "変更を保存" ,class: 'btn btn_orange rounded-pill w-50 m-auto my-2' %>
        </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>承認ステータス</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.select :is_confirmed, Campground.is_confirmeds.keys.map {|k| [I18n.t("enums.campground.is_confirmed.#{k}"), k]}, class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>却下理由(却下する場合のみ記載)</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_area :rejection_reason, autofocus: true, class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>キャンプ場画像</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.file_field :image, autofocus: true, accept: "image/*", class: "form-control-file" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>キャンプ場名</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>説明</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_area :description, autofocus: true, placeholder: "キャンプ場の説明", rows: "5", class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>住所</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :address, autofocus: true, placeholder: "東京都港区六本木３丁目２−１", class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>電話番号</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :phone_number, autofocus: true, placeholder: "例：XXX-XXXX-XXX", class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>営業時間</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :business_hours, autofocus: true, placeholder: "例：XX:XX~XX:XX", class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>チェックイン</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :check_in, autofocus: true, placeholder: "例：XX:XX~", class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>チェックアウト</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :check_out, autofocus: true, placeholder: "例：~XX:XX", class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>最寄り駅</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :station_line, autofocus: true, placeholder: "JR青梅", class: "form-control" %><%= f.label :"線" %>
              <%= f.text_field :station_name, autofocus: true, placeholder: "駅名", class: "form-control" %><%= f.label :"駅" %><br>
              <%= f.label :"徒歩" %><%= f.text_field :station_walk, autofocus: true, placeholder: "", class: "form-control" %><%= f.label :"分" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>最寄りバス停</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :busstop_line, autofocus: true, placeholder: "バス業者", class: "form-control" %>
              <%= f.text_field :busstop_name, autofocus: true, placeholder: "バス停名", class: "form-control" %><%= f.label :"バス停" %><br>
              <%= f.label :"徒歩" %><%= f.text_field :busstop_walk, autofocus: true, placeholder: "", class: "form-control" %><%= f.label :"分" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>キャンプ場URL</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :camp_url, autofocus: true, placeholder: "https~~", class: "form-control" %>
            </div>
          </div>

          <div class="row form-group mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>タグ</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.label :"(,で区切ると複数タグ登録できます)" %><br>
              <%= f.text_field :tag_name, autofocus: true, value: @tag_list, placeholder: "直火OK,ソロキャンプ", class: "form-control" %>
            </div>
          </div>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/campgrounds/index.html.erb
<div class="container">
  <div class="text-center p-1">
    <h3>キャンプ場一覧</h3>
    <%= link_to "+ キャンプ場新規作成",new_admin_campground_path, class: 'btn btn_orange rounded-pill w-50 m-auto my-2' %>
  </div>
  <div class="row mb-2">
    <div class="col-md-10">
      <table class="table table-hover table-light table-borderless">
        <thead>
            <tr>
              <th>キャンプ場名</th>
              <th>住所</th>
              <th>タグ</th>
              <th>レビュー件数</th>
              <th>承認ステータス</th>
            </tr>
        </thead>
        <tbody>
            <% @campgrounds.each do |campground| %>
            <tr>
              <td><%= link_to "#{campground.name}", admin_campground_path(campground.id) %></td>
              <td><%= campground.address %></td>
              <td>
                <i class="fas fa-tag"><%= campground.tags.map(&:tag_name).join(', ') %></i>
              </td>
              <td><%= "レビュー：#{campground.reviews.count}件" %></td>
              <td><%= campground.is_confirmed_i18n %></td>
            </tr>
            <% end %>
            <%= paginate @campgrounds %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/campgrounds/new.html.erb
<div class="container">
  <div class="text-center p-1">
    <h2>キャンプ場登録</h2>
  </div>
  <div class="row">
    <div class="col-md-8">
      <%= render 'layouts/campform', campground: @campground, url: admin_campgrounds_path %>

    </div>
  </div>
</div>

app/views/admin/campgrounds/show.html.erb
<div class="container">
  <div class="text-center p-1">
    <h3>キャンプ場詳細</h3>
  </div>
  <div class="row mb-2">
    <div class="col-md-8 mx-auto">
      <%= link_to "編集する", edit_admin_campground_path(@campground.id), class: "btn btn_orange rounded-pill w-50 m-auto my-2" %>
      <%= link_to "削除する", admin_campground_path(@campground.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn_water rounded-pill w-50 m-auto my-2" %>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>承認ステータス</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.is_confirmed_i18n %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>キャンプ場名</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.name %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>タグ</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <% @campground_tags.each do |tag| %>
            <i class="fas fa-tag">
              <span class="badge badge-pill"><%= tag.tag_name %></span>
            </i>
          <% end %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>説明</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.description %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>住所</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.address %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>電話番号</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.phone_number %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>営業時間</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.business_hours %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>チェックイン</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.check_in %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>チェックアウト</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.check_out %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>最寄り駅</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.station_line %>線
          <%= @campground.station_name %>駅
      徒歩<%= @campground.station_walk %>分
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-sm-3 col-5 text-left pl-2">
          <p>最寄りバス停</p>
        </div>
        <div class="col-sm-7 col-5 text-left px-0">
          <%= @campground.busstop_line %>
          <%= @campground.busstop_name %>バス停
      徒歩<%= @campground.busstop_walk %>分
        </div>
      </div>

    </div>
    <div class="col-md-2 mx-auto">
      <%= link_to campground_path(@campground) do %>
        <%= image_tag @campground.get_image(350, 350) %>
      <% end %>
    </div>
  </div>
</div>