config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'campgrounds#index'
    resources :users, only: [:index, :show, :update]
    resources :campgrounds, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :show, :destroy] do
      collection do
        get 'search'
      end
    end

  end

  scope module: :public do
    root to: 'homes#top'
    resource :users, only: [:show, :edit, :update] do
      collection do
        get 'favorite'
        get 'information/edit' => 'users#edit', as: 'edit'
        patch 'information/update' => 'users#update', as: 'update'
      end
    end
    resources :campgrounds, only: [:new, :index, :show, :create] do
      collection do
        get 'map'
        get 'thanks'
        get 'status'
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
    end
    resources :reviews, only: [:new, :index, :create, :destroy]
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_campform.html.erb
<%= form_with model: campground, url: url, class: 'new_campground', local: true do |f| %>
        <%= render "public/shared/error_messages", resource: @campground %>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>キャンプ場画像</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.file_field :image, autofocus: true, accept: "image/*", class: "form-control-file" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>キャンプ場名</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>説明</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_area :description, autofocus: true, placeholder: "キャンプ場の説明", rows: "5", class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>住所</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :address, autofocus: true, placeholder: "東京都港区六本木３丁目２−１", class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>電話番号</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :phone_number, autofocus: true, placeholder: "例：XXX-XXXX-XXX", class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>営業時間</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :business_hours, autofocus: true, placeholder: "例：XX:XX~XX:XX", class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>チェックイン</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :check_in, autofocus: true, placeholder: "例：XX:XX~", class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>チェックアウト</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :check_out, autofocus: true, placeholder: "例：~XX:XX", class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>最寄り駅</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :station_line, autofocus: true, placeholder: "JR青梅", class: "form-control" %><%= f.label :"線" %>
              <%= f.text_field :station_name, autofocus: true, placeholder: "駅名", class: "form-control" %><%= f.label :"駅" %><br>
              <%= f.label :"徒歩" %><%= f.text_field :station_walk, autofocus: true, placeholder: "", class: "form-control" %><%= f.label :"分" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>最寄りバス停</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :busstop_line, autofocus: true, placeholder: "バス業者", class: "form-control" %>
              <%= f.text_field :busstop_name, autofocus: true, placeholder: "バス停名", class: "form-control" %><%= f.label :"バス停" %><br>
              <%= f.label :"徒歩" %><%= f.text_field :busstop_walk, autofocus: true, placeholder: "", class: "form-control" %><%= f.label :"分" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>キャンプ場URL</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.text_field :camp_url, autofocus: true, placeholder: "https~~", class: "form-control" %>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-sm-3 col-5 text-left pl-2">
              <p>タグ</p>
            </div>
            <div class="col-sm-7 col-5 text-left px-0">
              <%= f.label :"(,で区切ると複数タグ登録できます)" %><br>
              <%= f.text_field :tag_name, autofocus: true, placeholder: "直火OK,ソロキャンプ", class: "form-control" %>
            </div>
          </div>

        <div class="actions">
          <%= f.submit "新規登録" ,class: 'btn btn_orange rounded-pill w-50 m-auto my-2' %>
        </div>
      <% end %>

app/views/layouts/_campindex.html.erb
<% campgrounds.each do |campground| %>
  <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4">
    <div class="card shadow bg-white rounded my-5">
      <%= link_to campground_path(campground) do %>
        <%= image_tag campground.get_image(350, 350) %>
      <% end %>
      <div class="card-body">
        <h4 class="card-title">
          <%= campground.name %>
        </h4>
        <div class="rating d-flex align-items-center m-2">
          <%= image_tag "star-on.png",class: "mr-2" %><%= campground.avg_score %> ( レビュー：<%= campground.reviews.count %>件 )
        </div>

        <div class="row mb-2">
          <div class="col-5 text-left pl-2">
            <p>タグ</p>
          </div>
          <div class="col-5 text-left px-0">
            <% campground.tags.each do |tag| %>
              <i class="fas fa-tag">
                <span class="badge badge-pill"><%= tag.tag_name %></span>
              </i>
            <% end %>
          </div>
        </div>

        <div class="row mb-2">
          <div class="col-5 text-left pl-2">
            <p>住所</p>
          </div>
          <div class="col-5 text-left px-0">
            <%= campground.address %>
          </div>
        </div>

        <div class="row mb-2">
          <div class="col-5 text-left pl-2">
            <p>電話番号</p>
           </div>
           <div class="col-5 text-left px-0">
             <%= campground.phone_number %>
           </div>
        </div>

        <div class="row mb-2">
           <div class="col-5 text-left pl-2">
             <p>チェックイン</p>
          </div>
          <div class="col-5 text-left px-0">
            <%= campground.check_in %>
          </div>
         </div>

        <div class="row mb-2">
          <div class="col-5 text-left pl-2">
            <p>チェックアウト</p>
          </div>
          <div class="col-5 text-left px-0">
            <%= campground.check_out %>
          </div>
        </div>

        <div class="row mb-2">
          <div class="col-5 text-left pl-2">
            <p>最寄り駅</p>
          </div>
          <div class="col-5 text-left px-0">
            <%= campground.station_line %>線<br>
            <%= campground.station_name %>駅<br>
        徒歩<%= campground.station_walk %>分
          </div>
        </div>

        <div class="row mb-2">
          <div class="col-5 text-left pl-2">
            <p>最寄りバス停</p>
          </div>
          <div class="col-5 text-left px-0">
            <%= campground.busstop_line %><br>
            <%= campground.busstop_name %>バス停<br>
        徒歩<%= campground.busstop_walk %>分
          </div>
        </div>

      </div>
     </div>
   </div>
<% end %>
<%= paginate campgrounds %>

app/views/layouts/_footer.html.erb
<p class="text-center">© 2023 徒歩キャン All Rights Reserved.</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" >

  <div class="container">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "camp-logo.png", size: "170x50" %>
        <% end %>

        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse align-items-center " id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <%= render 'layouts/header_admin' %>
          <% elsif user_signed_in? %>
            <%= render 'layouts/header_user' %>
          <% else %>
            <%= render 'layouts/header_unsign' %>
          <% end %>
         </ul>
        </div>

  </div>
</nav>

app/views/layouts/_header_admin.html.erb
<div class="btn-group" role="group" aria-label="Basic mixed styles example">
    <li class="nav-item">
      <%= link_to admin_root_path, class: 'nav-link text-dark' do %>
        <i class="fas fa-campground"></i> キャンプ場一覧
      <% end %>
    </li>
    <li class="nav-item">
      <%=  link_to admin_users_path, class: 'nav-link text-dark' do %>
        <i class="fas fa-user"></i> 会員一覧
      <% end %>
    </li>
    <li class="nav-item">
      <%=  link_to admin_reviews_path, class: 'nav-link text-dark' do %>
        <i class="fas fa-comment-dots"></i> レビュー一覧
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
        <i class="fas fa-arrow-right"></i> ログアウト（管理者）
      <% end %>
    </li>
</div>

app/views/layouts/_header_unsign.html.erb
<div class="d-flex flex-wrap">
  <i class="fas fa-search ms-2" style=" margin-top: 12px; margin-left: 8px; position:absolute;"></i>
  <div class="form-group form-inline">
    <%= search_form_for @q, url: search_campgrounds_path do |f| %>
      <%= f.search_field :name_or_tags_tag_name_cont, class: "form-control px-4", placeholder: ' タグ・名前で検索' %>
      <%= f.submit '検索', class: "form-control" %>
    <% end %>
  </div>
  <div class="btn-group" role="group" aria-label="Basic mixed styles example">
    <li class="nav-item">
      <%= link_to campgrounds_path, class: 'nav-link text-dark' do %>
        <i class="fas fa-campground"></i> キャンプ場一覧
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to users_guest_sign_in_path, method: :post, class: 'nav-link text-dark' do %>
        <i class="fas fa-user-tie"></i> ゲストログイン
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
        <i class="fas fa-solid fa-user-plus"></i> 新規登録
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to user_session_path, class: 'nav-link text-dark' do %>
        <i class="fas fa-sign-in-alt"></i>ログイン
      <% end %>
    </li>
  </div>
</div>

app/views/layouts/_header_user.html.erb
<div class="search d-flex flex-wrap">
  <i class="fas fa-search ms-2" style=" margin-top: 12px; margin-left: 8px; position:absolute;"></i>
  <div class="form-group form-inline">
    <%= search_form_for @q, url: search_campgrounds_path do |f| %>
      <%= f.search_field :name_or_tags_tag_name_cont, class: "form-control px-4", placeholder: ' タグ・名前で検索' %>
      <%= f.submit '検索', class: "form-control" %>
    <% end %>
  </div>
  <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <li class="nav-item">
        <%=  link_to campgrounds_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-campground"></i> キャンプ場一覧
        <% end %>
      </li>
      <li class="nav-item ml-1">
        <%=  link_to users_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-solid fa-user"></i> マイページ
        <% end %>
      </li>
      <li class="nav-item ml-1">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
          <i class="fas fa-solid fa-arrow-right"></i> ログアウト
        <% end %>
      </li>
  </div>
</div>

app/views/layouts/_reviews.html.erb
<div class="row">
  <div class="col-md-12">
    <% reviews.each do |review| %>
      <div class="card shadow bg-white rounded my-2">
        <div class="row mb-2">
          <div class="col-sm-6 col-md-3 m-3">
            <h5 class="fw-bold text-center"><%= review.title %></h5>
            <!--JavaScript呼び出し-->
            <div id="star-rate<%= review.id %>"></div>
              <p><%= review.star %> / 5.0</p>
            </div>
            <div class="col-sm-6 col-md-8 m-3">
              <div class="review_comment">
                <p><%= review.body %></p>
              </div>
            </div>
            <div class="col-sm-6 col-md-3 m-3">
              <% if review.user.profile_image.present? %>
                <%= image_tag review.user.profile_image, class:"rounded-circle", size:"50x50" %>
              <% else %>
                <i class="fas fa-user-plus fa-4x ms-3"></i>
              <% end %>
              <% if admin_signed_in? %>
                <p><%= link_to "#{review.user.name}さん", admin_user_path(review.user.id) %></p>
              <% else %>
                <p><%= review.user.name %> さん</p>
              <% end %>
            </div>
          </div>
        </div>
        <% if admin_signed_in? %>
          <div class="row ml-2">
             <!--レビューをAPIの分析結果によって色分けして表示-->
            <% if review.score.present? %>
              <% if review.score < -0.5 %>
                <span class="btn btn-danger rounded-pill w-50 m-auto mt-2"><%= review.score %>悪感情</span>
              <% elsif review.score > 0.5 %>
                <span class="btn btn-success rounded-pill w-50 m-auto mt-2"><%= review.score %>良感情</span>
              <% else %>
                <span class="btn btn-info rounded-pill w-50 m-auto mt-2"><%= review.score %>普感情</span>
              <% end %>
            <% end %>
            <%= link_to "レビューを削除する", admin_review_path(review.id), method: :delete, class: "btn btn_orange rounded-pill w-50 m-auto mt-2" %>
          </div>
        <% end %>
        <% if user_signed_in? && review.user_id == current_user.id %>
          <div class="row ml-2">
            <%= link_to "レビューを削除する", review_path(review.id), method: :delete, class: "btn btn_orange rounded-pill w-50 m-auto mt-2" %>
          </div>
        <% end %>
      <script>
        let elem<%= review.id %> = document.querySelector('#star-rate<%= review.id %>');
        let opt<%= review.id %> = {
          size: 36,
          starOff: '<%= asset_path('star-off.png') %>',
          starOn: '<%= asset_path('star-on.png') %>',
          readOnly: true,
          score: <%= review.star %>,
          half: false,
        };
        raty(elem<%= review.id %>, opt<%= review.id %>);
      </script>
    <% end %>
    <%= paginate reviews %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>徒歩キャン△</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7b631ea962.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main>
      <div class="text-center text-info mb-2">
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>